REPLACE INTO `roles` VALUES (1,'ADMIN');

INSERT INTO CATEGORIA (ID, NOMBRE) VALUES (1,'Portátiles');

INSERT INTO EDIFICIO (ID, NOMBRE, UBICACION) VALUES (007,'SFJ','AVENIDA AMERICA');
INSERT INTO EDIFICIO (ID, NOMBRE, UBICACION) VALUES (006,'PRA','PRADILLO 40');


INSERT INTO PERSONA (LOGIN, NOMBRE, APELLIDOS, TELEFONO, DESPACHO, PUESTO,TIPO,EDIFICIO_ID ) VALUES ('malonso','Miguel','Alonso','602569654','504','Jefe','PERSONA',007);

INSERT INTO PERSONA (LOGIN, NOMBRE, APELLIDOS, TELEFONO, NIVEL,TIPO,EDIFICIO_ID,INCIDENCIAS ) VALUES ('cdelcampo','Carlos','Del Campo','602569654','EXPERTO','TECNICO',006,0);
INSERT INTO PERSONA (LOGIN, NOMBRE, APELLIDOS, TELEFONO, NIVEL,TIPO,EDIFICIO_ID,INCIDENCIAS ) VALUES ('mjanto','Maria','Janto','602569654','BASICO','TECNICO',006,1);
INSERT INTO PERSONA (LOGIN, NOMBRE, APELLIDOS, TELEFONO, NIVEL,TIPO,EDIFICIO_ID,INCIDENCIAS ) VALUES ('imartinez','Isabel','Martinez','602569654','EXPERTO','TECNICO',006,2);
INSERT INTO PERSONA (LOGIN, NOMBRE, APELLIDOS, TELEFONO, NIVEL,TIPO,EDIFICIO_ID,INCIDENCIAS ) VALUES ('bmiguel','Beatriz','Miguel','602569654','EXPERTO','TECNICO',006,2);
INSERT INTO PERSONA (LOGIN, NOMBRE, APELLIDOS, TELEFONO, NIVEL,TIPO,EDIFICIO_ID,INCIDENCIAS ) VALUES ('palonso','Pablo','Alonso','602569654','BASICO','TECNICO',007,5);
INSERT INTO PERSONA (LOGIN, NOMBRE, APELLIDOS, TELEFONO, NIVEL,TIPO,EDIFICIO_ID,INCIDENCIAS ) VALUES ('gperez','Gabriel','Perez','602569654','EXPERTO','TECNICO',007,0);


INSERT INTO PRODUCTO (ID, MARCA, MODELO,STOCK, CANTIDAD,CATEGORIA_ID,EDIFICIO_ID) VALUES ('100','HP','430',5,0,1,007);

INSERT INTO INCIDENCIA (ID, DESCRIPCION, FECHA_INICIO, FECHA_FIN,PRIORIDAD,ESTADO,TIPO,LOGIN,LOGIN_TECNICO) VALUES ('9996','NO FUNCIONA','2015-02-25','2018-08-02','ALTA','ABIERTA','RED','malonso','cdelcampo');
